export class Measure {

  constructor(
    public pesoActual: number,
    public talla: number,
    public tallaSentado: number,
    public envergadura: number,
    public imc: number,
    public acromialRadial: number,
    public radialEstiloidea: number,
    public medialEstiloideaDactilar: number,
    public ilioespinal: number,
    public trocanterea: number,
    public trocantereaTrivialLateral: number,
    public tribialLateral: number,
    public tribialMedialMaleolarMedial: number,
    public pie: number,
    public biacromial: number,
    public toraxTransverso: number,
    public toraxAnteroposterior: number,
    public biIliocrestidio: number,
    public humeral: number,
    public femoral: number,
    public munecaBiestiloideo: number,
    public tobilloBiestiloideo: number,
    public cabeza: number,
    public cuello: number,
    public brazoRelajado: number,
    public brazoFlexEnTension: number,
    public antebrazo: number,
    public muneca: number,
    public toraxMesoesternal: number,
    public cinturaMinima: number,
    public abdominalMaximo: number,
    public caderasMaxima: number,
    public musloSuperior: number,
    public musloMedial: number,
    public pantorrillaMaxima: number,
    public tobilloMinima: number,
    public triceps: number,
    public subescapular: number,
    public biceps: number,
    public crestaIliaca: number,
    public supraespinal: number,
    public abdominal: number,
    public musloAnterior: number,
    public pantorrilla: number,
    public date: string,
    public others: string,
    public pacientId?: string,
    public img?: string,
    public _id?: string
  ) {}

}
